/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: /9UDOyCKwFE94ojbjb+Nr0nahh5kTyrEZNxmXORiSXN3WocPyDYfLxD8LuQDH9rdr9/sXVVDLP0a2xwhAtYQvQ==
 */

/* eslint-disable */
// tslint:disable

import Users, {Users_InsertParameters} from './users'

interface DatabaseSchema {
  users: {record: Users, insert: Users_InsertParameters};
}
export default DatabaseSchema;

function serializeValue(_tableName: string, _columnName: string, value: unknown): unknown {
  return value;
}
export {serializeValue}

export type {
  Users,
  Users_InsertParameters,
}
