/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: C3R0vEgXvI5MsibKEl2/abG6mTMscciyVaDNW3MOXr+/tVejJ0ARswTCVa64H7r/un8NShHU1n1UeXxLHQd/CA==
 */

/* eslint-disable */
// tslint:disable

import UserTokens, {UserTokens_InsertParameters} from './user_tokens'
import Users, {Users_InsertParameters} from './users'

interface DatabaseSchema {
  user_tokens: {record: UserTokens, insert: UserTokens_InsertParameters};
  users: {record: Users, insert: Users_InsertParameters};
}
export default DatabaseSchema;

function serializeValue(_tableName: string, _columnName: string, value: unknown): unknown {
  return value;
}
export {serializeValue}

export type {
  UserTokens,
  UserTokens_InsertParameters,
  Users,
  Users_InsertParameters,
}
