/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 8DLWUC8Whn29W4VBoAwjmsXC3IhPmzp7vDeyyfvnlBuaT/Q+JJ+4hb1VWQOKJKyayBJQ5ZNmp0527MwuTowpIw==
 */

/* eslint-disable */
// tslint:disable

interface Users {
  created_on: number
  email: (string) | null
  /**
   * @default nextval('users_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'users_id'}
  password_hash: string
  profile_picture: (string) | null
  username: (string) | null
}
export default Users;

interface Users_InsertParameters {
  created_on: number
  email?: (string) | null
  /**
   * @default nextval('users_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'users_id'}
  password_hash: string
  profile_picture?: (string) | null
  username?: (string) | null
}
export type {Users_InsertParameters}
