/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: aZX5PF5Qp7RPQKEb6OdlwvJich5bF2lGJn95SjPzAlG5yoCanHQEWiiwVwIwcEVLfZEBeeW3b1V02B/WznZVdw==
 */

/* eslint-disable */
// tslint:disable

import Users from './users'

interface UserTokens {
  expires_on: number
  token: string
  user_id: Users['id']
}
export default UserTokens;

interface UserTokens_InsertParameters {
  expires_on: number
  token: string
  user_id: Users['id']
}
export type {UserTokens_InsertParameters}
