server:
  name: 'http://localhost:3000'          # This is the 'local audience' or public address the server is named
  port: 3000                             # This is the port the expressJS server will bind to.

cors:
  origin: ['http://localhost:4000', 'http://localhost:5000']      # Requests from these origins are allowed.

auth:
  tokenSecret: 'app_secret_here'         # This is the secret used for signing JWTs by the server.
  audiences: ['http://localhost:3000']  # The audiences we attach to the JWT token.

database:
  name: 'portal'
  host: '192.168.1.50'
  port: 5432
  user: 'bitmuse'
  password: 'this-is-a-dumb-password'